### ISSUE TITLE
[Feature] Amazon Ads v2 -> v3 Schema Change Updates Required

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_amazon_ads_source#9]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Amazon Ads is upgrading from their V2 to V3 API. This is resulting in a number of deprecations and new field additions. For a full list of changes you can view the [planned deprecations for the Amazon Ads API](https://advertising.amazon.com/API/docs/en-us/info/deprecations).

For this package (and likely the downstream dbt_amazon_ads package), the following changes will need to be made to reflect the connector changes:

- CAMPAIGN_HISTORY table
  - Removed Fields: 
    - Campaign_type, daily_budget, placement, premium_bid_adjustment
  - Added Fields: 
    - Budget, budget_type, effective_budget

- KEYWORD_HISTORY
  - Added Fields: 
    - native_language_locale

### Describe alternatives you've considered

This will still likely work following the API upgrade, but it would be best to upgrade to ensure our package is using the latest fields provided by the API and connector.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-catfritz** [comment]
Also throwing a note on here that data types in the macros will need to be updated for several id columns. List [here](https://fivetran.com/docs/applications/amazon-ads/changelog#june2023).
